# Generated by Django 5.0.4 on 2024-04-14 01:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('mobile', models.IntegerField(max_length=10, verbose_name='Mobile No.')),
                ('userId', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskdetail', models.TextField(verbose_name='Detail')),
                ('tasktype', models.CharField(choices=[('Pending', 'Pending'), ('Done', 'Done')], max_length=10, verbose_name='Status')),
                ('taskassign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='app.user')),
            ],
        ),
    ]
