# Generated by Django 5.0.4 on 2024-04-14 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='task',
            table='Task',
        ),
        migrations.AlterModelTable(
            name='user',
            table='User',
        ),
    ]
