# Generated by Django 5.0.4 on 2024-04-14 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_task_table_alter_user_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='taskassign',
            new_name='task_Assign',
        ),
    ]
