# Generated by Django 5.0.4 on 2024-04-14 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_taskassign_task_task_assign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.IntegerField(verbose_name='Mobile No.'),
        ),
    ]
